# Generated by Django 4.1 on 2022-08-27 21:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lib_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aut_name', models.CharField(max_length=30)),
                ('aut_gender', models.BooleanField(default=False)),
                ('aut_age', models.IntegerField()),
                ('aut_comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bor_name', models.CharField(max_length=30)),
                ('bor_gender', models.BooleanField(default=False)),
                ('bor_age', models.IntegerField()),
                ('bor_comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LenderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('len_name', models.CharField(max_length=30)),
                ('len_gender', models.BooleanField(default=False)),
                ('len_age', models.IntegerField()),
                ('len_comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='bor_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='is_bor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='len_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='borrower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lib_sys.borrowerinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='lender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lib_sys.lenderinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bauthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_sys.authorinfo'),
        ),
    ]
